"""Generate MOAT.md: which sources are worth recording, and which are not.

The test is one question. If we ask this source the same question in a year, do
we get today's answer back? Where the answer is yes, recording is storage spent
on a copy of something the publisher will hand anyone for free. Where the answer
is no, the history exists only if something was running, and that is an asset
nobody can buy, backfill or compete away by starting later.

The classification is derived from the registry's own `point_in_time` field, so
it cannot drift from what the code actually says. The list of things we record
lives in `vintage.archive.targets`, and this script fails if the two disagree.

    uv run python tools/moat_study.py
"""

from __future__ import annotations

import os
import sys
from datetime import date

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from vintage import archive, registry  # noqa: E402

# Why a source that keeps no vintage is worth the disk, in the terms that decide
# it: what a researcher cannot do without the recording, and who else has it.
WORTH = {
    "sec-edgar-sic": (
        "highest",
        "Point-in-time industry labels",
        "EDGAR states the current SIC code and no date of change. Every "
        "cross-sectional neutralisation needs to know what industry a name was "
        "in *then*, and the alternative, GICS, is licensed from S&P and MSCI. "
        "Recording the code weekly builds the only free point-in-time "
        "classification there is.",
    ),
    "apewisdom": (
        "high",
        "Retail attention history",
        "There is no history endpoint and no vendor selling last Tuesday's "
        "board. A year of hourly reads is a year nobody starting today can have.",
    ),
    "sec-xbrl-frames": (
        "high",
        "Point-in-time cross-sections",
        "A frame is every filer on one concept, carrying the accession but not "
        "its filing date. Snapshotting it dates the cross-section, which is "
        "exactly what a sort needs and what the endpoint refuses to give.",
    ),
    "yahoo-finance": (
        "high",
        "Prices as they were printed",
        "Every close is re-adjusted the morning after a split or dividend, so "
        "today's history is not the history anyone traded on. Recording the "
        "close as printed keeps the unadjusted series, which no free source has.",
    ),
    "ken-french-data-library": (
        "medium",
        "Factor file vintages",
        "The files are rebuilt on each release. A factor return can change with "
        "no record that it did, and a replication against today's file is not a "
        "replication of the paper.",
    ),
    "coinbase-exchange": (
        "medium",
        "Crypto survivorship",
        "Only currently-listed products are returned, so dead tokens vanish "
        "entirely. Recording the product list is the only way to know what was "
        "tradable then.",
    ),
    "bea": (
        "low",
        "GDP revision history",
        "Real value, but ALFRED already keeps the vintages through `fred:`, so "
        "recording it duplicates a source that is already honest.",
    ),
    "bls": (
        "low",
        "CPI and payroll first prints",
        "Same as BEA: worth having, already available with vintages through "
        "`fred:`. Record only if the FRED dependency becomes a problem.",
    ),
}

RANK = {"highest": 0, "high": 1, "medium": 2, "low": 3}


def keeps_its_own_history(source: dict) -> bool:
    """Does asking again in a year still return today's answer?"""
    pit = str(source.get("point_in_time", "")).lower()
    return pit.startswith("yes")


def main() -> None:
    recordable, settled = [], []
    for src in registry.SOURCES:
        (settled if keeps_its_own_history(src) else recordable).append(src)

    recordable.sort(key=lambda s: RANK.get(WORTH.get(s["source"], ("low",))[0], 9))

    covered = set(archive.COVERS.values())
    missing = [s["source"] for s in recordable
               if WORTH.get(s["source"], ("low",))[0] in ("highest", "high")
               and s["source"] not in covered]

    rows = []
    for src in recordable:
        worth, what, why = WORTH.get(src["source"], ("low", "—", "Not yet assessed."))
        rows.append(f"| **{src['source']}** | `{src['field_form'].split()[0]}` | "
                    f"{worth} | {what} | {why} |")

    kept = "\n".join(
        f"| `{slug}` | {cadence} | {why} |" for slug, cadence, why, _ in archive.targets())

    body = f"""# The moat

Which sources are worth recording, and which are not. Generated by
`tools/moat_study.py` from the registry's own `point_in_time` field, so it cannot
drift from what the code says. Last run {date.today().isoformat()}.

## The test

> Ask this source the same question in a year. Do we get today's answer back?

Where the answer is **yes**, recording is storage spent on a copy of something
the publisher hands anyone for free. Fourteen of Vintage's nineteen sources are
in that group, and they are the reason this file is short.

Where the answer is **no**, the history exists only because something was
running. That is not a licence anyone can buy, a page anyone can scrape late, or
an advantage anyone starting tomorrow can close. It only gets deeper.

## Worth recording

{chr(10).join(['| Source | Prefix | Worth | What it buys | Why the publisher will not give it to you later |',
               '|---|---|---|---|---|'] + rows)}

## Already recording

`vintage.archive.targets` is the live list. Storage is not the constraint: the
four below write on the order of a hundred kilobytes a day before compression,
so a decade costs less than a phone's worth of photos. Continuity is the
constraint, and a missed week cannot be filled in afterwards.

| Target | Cadence | What is lost if it stops |
|---|---|---|
{kept}

## Not worth recording

These keep their own history, so recording them buys nothing:

{", ".join("`" + s["source"] + "`" for s in settled)}.

## How it is stored

Append-only, bitemporal, gzipped JSONL partitioned by the UTC date of the read.

- A value identical to the last one recorded for the same
  `(entity, field, observed_at)` is not written again. An industry code that
  moves once a decade costs almost nothing; a mention count that moves hourly
  costs its full size.
- A partition is never rewritten once its day closes, so every file is immutable
  and cacheable forever.
- A source that cannot say when a value became public gets its `known_at` from
  the moment we read it, marked `vintage: recorded-at-read`. The row is not
  point-in-time back to its origin, and it does not claim to be. It is
  point-in-time from the day recording started.
"""

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "MOAT.md")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print(f"wrote {path} ({len(body):,} bytes)")
    print(f"{len(recordable)} worth recording, {len(settled)} keep their own history, "
          f"{len(covered)} being recorded now")
    if missing:
        # Not a warning to be read and forgotten: a high-value source that is not
        # being recorded is a day of history being lost while you read this.
        print(f"NOT YET RECORDED but rated high: {', '.join(missing)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
